# Generated by Django 4.2.6 on 2024-10-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
