# Generated by Django 4.2.6 on 2024-10-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_management', '0003_department_created_at_department_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
