# Generated by Django 4.2.6 on 2024-10-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_management', '0004_alter_institution_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(default='hod@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
